name: seqlib
channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
  - future
  - requests
  - cython
  - pandas
  - bedtools
  - ucsc-bedtobigbed
  - ucsc-bedgraphtobigwig
  - pysam>=0.8.4
  - pybedtools>=0.7.8
  - msgpack-python
  - docopt
  - beautifulsoup4
  - lxml
  - coverage
  - pytest
  - pytest-cov
  - pytest-flake8
  - codecov
  - pip:
    - pytest-helpers-namespace

